name:                lab-crud-app
version:             0.1.0.0
github:              "university/lab-crud-app"
license:             BSD3
author:              "Student"
maintainer:          "student@university.edu"

extra-source-files:
- README.md

description:         Computer Lab Schedule Management System

dependencies:
- base >= 4.7 && < 5
- mysql-haskell >= 1.1.3
- io-streams >= 1.5
- network >= 3.1
- text >= 2.0
- bytestring >= 0.11
- time >= 1.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lab-crud-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab-crud-app
