name:                lab2-dijkstra
version:             1.0.0
github:              "university/lab2-dijkstra"
license:             MIT
author:              "Student"
maintainer:          "student@example.com"

extra-source-files:
- README.md

description:         Parallel Dijkstra's Algorithm Implementation

dependencies:
- base >= 4.14 && < 5
- containers >= 0.6
- parallel >= 3.2
- deepseq >= 1.4
- clock >= 0.8
- random >= 1.2

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src

executables:
  lab2-dijkstra-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab2-dijkstra
